services:
  wafer-movie-api:
    container_name: wafer-movie-api
    image: ghcr.io/mohammad-hosein-shahpouri/wafer-movie-api:v${IMAGE_TAG}
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: ./Src/WaferMovie.Web/Dockerfile
    environment:
      TZ: Asia/Tehran
      ASPNETCORE_URLS: http://+:8080;https://+:8443;
    restart: always
    hostname: wafer-movie
    networks:
      - wafer-movie
    volumes:
      - wafer-movie-api-logs:/app/logs
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17-alpine
    restart: always
    networks:
      - wafer-movie
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: WaferMovie
      POSTGRES_PASSWORD: Qwer@#1234
      POSTGRES_DB: WaferMovie.App
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4-alpine
    restart: always
    networks:
      - wafer-movie
    ports:
      - "6379:6379"

networks:
  wafer-movie:
  
volumes:
  postgres-data:
  wafer-movie-api-logs: