version: '3.9'

services:
    web:
        container_name: web
        build:
            context: ./
            dockerfile: Dockerfile
        restart: always
        hostname: wafer-movie
        ports:
            - 80:8000