version: "3.9"

services:
    postgres:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_USER: WaferMovie
            POSTGRES_PASSWORD: J%pH63EUXk1WzR6t
            POSTGRES_DB: WaferMovie.App
        ports:
            - "5432:5432"

    redis:
        image: redis:apline
        restart: always
        ports:
            - "6379:6379"