<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>0a1bb62d-54c8-46c2-903c-682af5bc91a5</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WaferMovie.Application\WaferMovie.Application.csproj" />
		<ProjectReference Include="..\WaferMovie.Infrastructure\WaferMovie.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="NewFolder\" />
	</ItemGroup>

</Project>
