name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
      
    - name: Generate Test Report
      uses: dorny/test-reporter@v1.5.0
      with:
        name: Test Results
        path: '**/test-results.trx'
        reporter: dotnet-trx
  